<?php
require_once('core/boot.php');
?>
<html>
<head></head>
<body>
<table class="table table-striped">
<tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
</tr>
    <tr>
        <td>Manikandan</td>
        <td>1234567890</td>
        <td>manir@gmail.comm</td>
    </tr>
    <tr>
        <td>Sudhakar Ilango</td>
        <td>1234567890</td>
        <td>sudhakar@gmail.comm</td>
    </tr>
    <tr>
        <td>Arun Kumar</td>
        <td>1234567890</td>
        <td>arun@gmail.com</td>
    </tr>
    <tr>
        <td>Manikandan</td>
        <td>1234567890</td>
        <td>manik@gmail.com</td>
    </tr>
    <tr>
        <td>Kavin</td>
        <td>1234567890</td>
        <td>kavin@gmail.com</td>
    </tr>
    <tr>
        <td>Surendharan</td>
        <td>1234567890</td>
        <td>surendharan@gmail.com</td>
    </tr>
    <tr>
        <td>Raj</td>
        <td>1234567890</td>
        <td>raj@gmail.com</td>
    </tr>
    <tr>
        <td>Rahu</td>
        <td>1234567890</td>
        <td>Rahu@ymail.com</td>
    </tr>
    
</table>
</body>
</html>